---
- url: vintage-and-modern
  title: I Was Eaten By a Shark!
  date: July 04 2011
- url: look-whos-taking-the-f-train
  title: Motherfuckin Placeholder Text Motherfucker! 
  date: October 22 2010
- url: im-engaged
  title: Uuummmm, this is a tasty burger!
  date: March 22 2011
- url: hows-it-taste
  title: How's it Taste Mothafucka?
  date: April 01 2012
