---
- url: java
  title: java
  date: May 12 2011
- url: interior-design-inspiration
  title: interior design ideas
  date: July 04 2011
- url: september-wedding
  title: my september wedding
  date: November 27 2011
- url: october
  title: october
  date: November 28 2011
- url: november-december-january
  title: november, december, january
  date: January 31 2012
- url: my-new-website
  title: welcome to my new website
  date: April 29 2012
- url: a-new-chapter
  title: a new chapter
  date: July 15 2012
- url: how-to-not-be-an-awesome-landlord
  title: how to not be an awesome landlord
  date: August 31 2012
- url: valentines
  title: Ian's Secret Skills
  date: February 14 2012