---
- id: themuse
  alt: The Muse
  thumbnail: /images/portfolio/web/themuse.png
  img: /images/portfolio/web/themuse.jpg
  title: Design&nbsp;&#38;&nbsp;Development&nbsp;&nbsp;&#47;&#47;&nbsp;&nbsp;The Muse
  description: >
    <p>As the Senior Frontend Engineer I deliver Backbone HTML, SASS, and JavaScript via JQuery and CoffeeScript for our Python / Tornado based app. When not strictly coding, I switch to designing from concept to implementation.</p><p><a href='http://themuse.com/' target='_blank'>The Muse</a> provides an engaging job board showcasing the company culture of hiring profiles through photos and video as well as smart career advice for professional development.</p><br /><a href="http://themuse.com/" target="_blank">http://www.themuse.com</a><br /><br />
- id: newlywish
  alt: Newlywish
  thumbnail: /images/portfolio/web/newlywish.png
  img: /images/portfolio/web/newlywish.jpg
  title: Development&nbsp;&nbsp;&#47;&#47;&nbsp;&nbsp; Newlywish
  description: >
    <p>NewlyWish is a gift registry service designed to provide to-be-weds, their friends and family, and just about anyone who wants a registry, with amazing products, experiences, and alternative gift giving, such charities donations and cash funds. This application was designed and implemented, full-stack, by my amazingly talented husband <a href="http://www.ianenders.com" target="_blank">Ian Enders</a>.</p><p>I lend a helping hand (or eye) on QA testing particularly after features get launched.</p><br /><a href="http://www.newlywish.com/" target="_blank">http://www.newlywish.com</a><br /><br />
- id: hackbright
  alt: Hackbright Academy
  thumbnail: /images/portfolio/web/hackbright.png
  img: /images/portfolio/web/hackbright.jpg
  title: Logo Design&nbsp;&nbsp;&#47;&#47;&nbsp;&nbsp;Hackbright Academy
  description: >
    <p>I was contracted to design a logo for this super awesome all-girl programing academy. As a new institution, there was a lot of emphasis on getting the branding and logo just right. I wanted the logo to be feminine yet gender neutral enough in the event that they open the course to men as well.</p><br /><a href="http://hackbrightacademy.com/" target="_blank">http://www.hackbrightacademy.com</a><br /><br />
- id: tiffany
  alt: Tiffany Ring Finder  
  thumbnail: /images/portfolio/web/tiffany.png
  img: /images/portfolio/web/tiffany.jpg
  title: Development&nbsp;&nbsp;&#47;&#47;&nbsp;&nbsp;Tiffany &#38; Co. Ring Finder
  description: >
    <p>The Ring Finder app is a private voting application wrapped inside of facebook or as a standalone web page. A user would create a list of rings they like using the iPhone Ring Finder app, and share it with their friends by emailing a unique URL, which link guests to the web or facebook, depending on how one logs on. There, people can vote and comment on their favorite rings. My role included writing the views (HTML/CSS) on a Rails framework for the web UI.</p>
- id: juicegeneration
  alt: Tiffany Ring Finder  
  thumbnail: /images/portfolio/web/juicegeneration.png
  img: /images/portfolio/web/juicegeneration.jpg
  title: Development&nbsp;&nbsp;&#47;&#47;&nbsp;&nbsp;Juice Generation
  description: >
    <p>Developed the front end of this detox juice-centric e-commerce site by writing the HTML, CSS, basic Ruby and some Javascript(JQuery) for the user interface.</p><a href="http://juicegeneration.com/" target="_blank">http://juicegeneration.com</a><br /><br />
- id: scully
  alt: Scully and Scully
  thumbnail: /images/portfolio/web/scully.png
  img: /images/portfolio/web/scully.jpg
  title: Development&nbsp;&nbsp;&#47;&#47;&nbsp;&nbsp;Juice Generation
  description: >
    <p>Partnered with <a href="http://intersectnyc.com" target="_blank">Intersect NYC</a> to develop the frontend by writing HTML, CSS, and some very basic Ruby and JavaScript(JQuery) to produce web compliant Rails views.</p><a href="http://www.scullyandscully.com/" target="_blank">http://www.scullyandscully.com</a><br /><br />
- id: mally
  alt: Mally Beauty
  thumbnail: /images/portfolio/web/mally.png
  img: /images/portfolio/web/mally.jpg
  title: Development&nbsp;&nbsp;&#47;&#47;&nbsp;&nbsp;Mally Beauty
  description: >
    <p>Mally Beauty take two, a redesign of the old Mally, which I also worked on (see below). This redesign presents a slicker user interface and focuses heavily on social networking. Partnered with <a href="http://intersectnyc.com" target="_blank">Intersect NYC</a> to develop the frontend by writing HTML, CSS, and some very basic Ruby and JavaScript(JQuery) to produce web compliant Rails views.</p><a href="http://www.mallybeauty.com/" target="_blank">http://www.mallybeauty.com</a><br /><br />
- id: kiko
  alt: kico kids
  thumbnail: /images/portfolio/web/kicokids.png
  img: /images/portfolio/web/kicokids.jpg
  title: Development&nbsp;&nbsp;&#47;&#47;&nbsp;&nbsp;Kico Kids
  description: >
    <p>Partnered with <a href="http://intersectnyc.com" target="_blank">Intersect NYC</a> to develop the frontend by writing HTML, CSS, and some very basic Ruby and JavaScript(JQuery) to develop the frontend by writing HTML, CSS, and some very basic Ruby and JavaScript(JQuery) to produce web compliant Rails views for this kid's clothing e-commerce site.</p>
- id: ajaline
  alt: ajaline
  thumbnail: /images/portfolio/web/ajaline.png
  img: /images/portfolio/web/ajaline.jpg
  title: Development&nbsp;&nbsp;&#47;&#47;&nbsp;&nbsp;Ajaline
  description: >
    <p>Partnered with <a href="http://intersectnyc.com" target="_blank">Intersect NYC</a> to develop the frontend by writing HTML, CSS, and some very basic Ruby and JavaScript(JQuery) to produce web compliant Rails views for this exclusive high-end fine jewelry site.</p>
- id: satellite
  alt: satellite records
  thumbnail: /images/portfolio/web/satellite_records.png
  img : /images/portfolio/web/satellite.jpg
  title: Development&nbsp;&nbsp;&#47;&#47;&nbsp;&nbsp;Satellite Records
  description: >
    <p>Satellite Records is a major player in the industry of digital download music with DJ's all around the world as its target audience. I contributed to the the frontend by writing HTML, CSS, to produce web compliant Rails views.</p><a href="http://www.satelliterecords.com/" target="_blank">http://www.satelliterecords.com</a><br /><br />
- id: kenneth_cole
  alt: kenneth cole
  img: /images/portfolio/web/kenneth_cole.jpg
  thumbnail: /images/portfolio/web/kenneth_cole.png
  title: Development&nbsp;&nbsp;&#47;&#47;&nbsp;&nbsp;Kenneth Cole
  description: >
    <p>For this rails application I implemented the user interface by writing web compliant Rails views in HTML, CSS, and some very basic Ruby and JavaScript(JQuery) to create a website, a facebook page, and an interface for mobile devices, namely Webkit and Blackberry. Partnered with <a href="http://www.intersectnyc.com" target="_blank">Intersect NYC.</a>
- id: bobbi_brown
  alt: bobbi brown
  img: /images/portfolio/web/bobbi_brown.jpg
  thumbnail: /images/portfolio/web/bobbi_brown.png
  title: Development&nbsp;&nbsp;&#47;&#47;&nbsp;&nbsp;Bobbi Brown
  description: >
    <p>As a temporary administrator for Bobbi Brown's facebook page, I created a custom tab called Beauty Rules and reconfigured third party HTML to work within the Facebook framework. Partnered with <a href="http://www.intersectnyc.com" target="_blank">Intersect NYC.</a></p><a href="http://www.facebook.com/BobbiBrown?v=app_6009294086&ref=ts/" target="_blank">http://www.facebook.com/BobbiBrown?v=app_6009294086&ref=ts</a><br /><br />
- id: yigal
  alt: yigal azrouel
  img: /images/portfolio/web/yigalazrouel.jpg
  thumbnail: /images/portfolio/web/yigalazrouel.png
  title: Development&nbsp;&nbsp;&#47;&#47;&nbsp;&nbsp;Yigal Azrouel
  description: >
    <p>Partnered with <a href="http://intersectnyc.com" target="_blank"> Intersect NYC</a> to develop the frontend by writing HTML, CSS, and some very basic Ruby and JavaScript(JQuery) to produce web compliant Rails views for this high-end fashion design site.</p><a href="http://www.yigal-azrouel.com/" target="_blank">http://www.yigal-azrouel.com</a><br /><br />
- id: boast
  alt: boast
  img: /images/portfolio/web/boast.jpg
  thumbnail: /images/portfolio/web/boast.png
  title: Development&nbsp;&nbsp;&#47;&#47;&nbsp;&nbsp;Boast USA
  description: >
    <p>Took an existing Rails e-commerce framework and re-skinned it to make this site. Other than the designers involved in the making of Boast, little backend support was required, which made the development phase for the most part a rare solo project. Developed the frontend by writing HTML, CSS, and some very basic Ruby and JavaScript(JQuery) to produce web compliant Rails views in partnership with <a href="http://intersectnyc.com" target="_blank">Intersect NYC</a>.</p><a href="http://www.boastusa.com/" target="_blank">http://www.boastusa.com</a><br /><br />
- id: lanecrawford
  alt: lane crawford
  img: /images/portfolio/web/lanecrawford.jpg
  thumbnail: /images/portfolio/web/lanecrawford.png
  title: Development&nbsp;&nbsp;&#47;&#47;&nbsp;&nbsp;Lane Crawford
  description: >
    <p>Lane Crawford Heritage 160 is a micro site that lives under the umbrella site <a href="http://www.lanecrawford.com/">http://www.lanecrawford.com</a>. For this site, I wrote HTML, CSS, and incorporated third party XML, SWF and flash files. Partnered with <a href="http://intersectnyc.com" target="_blank">Intersect NYC.</a></p>
- id: lanecrawford_teaser
  alt: lane crawforteaser")
  img: /images/portfolio/web/lanecrawford_teaser.jpg
  thumbnail: /images/portfolio/web/lanecrawford_teaser.png
  title: Development&nbsp;&nbsp;&#47;&#47;&nbsp;&nbsp;Lane Crawford Teaser
  description: >
    <p>Lane Crawford Teaser was the prelude to Lane Crawford Heritage 160, a micro site that lives under the umbrella site <a href="http://www.lanecrawford.com/">http://www.lanecrawford.com</a>. For this site, I wrote the HTML and CSS. Partnered with <a href="http://intersectnyc.com" target="_blank">Intersect NYC</a>.</p>
- id: grandsf
  alt: grand sf
  img: /images/portfolio/web/grandsf.jpg
  thumbnail: /images/portfolio/web/grandsf.png
  title: Development&nbsp;&nbsp;&#47;&#47;&nbsp;&nbsp;Grand SF
  description: >
    <p>Fot Grand SF I wrote the HTML5 video player and encoded other formats of videos, such as mp4 and ogg type, to supplement flash video for browsers that are HTML5 compatible. Developed in partnership with <a href="http://intersectnyc.com" target="_blank">Intersect NYC</a>.</p>
      <a href="http://www.agrandsite.com/" target="_blank">http://www.agrandsite.com</a><br /><br />
- id: luckyzinc
  alt: lucky zinc
  img: /images/portfolio/web/luckyzinc.jpg
  thumbnail: /images/portfolio/web/luckyzinc.png
  title: Development&nbsp;&nbsp;&#47;&#47;&nbsp;&nbsp;Lucky Insider
  description: >
    <p>Lucky Magazine and American Express teamed up to create this site to promote the zync credit card. Much like its predecessor <a href="http://http://stylespotter.luckymag.com/" target="_blank">Lucky Style Spotter</a>, it focuses on users uploaded looks and the expert advice given regarding their style. Collaborated with <a href="http://intersectnyc.com" target="_blank">Intersect NYC</a>to implement the re-skinning of the user interface by writing HTML, CSS and basic Ruby for the frontend.</p>
      <a href="http://zync.luckylookout.com/" target="_blank">http://zync.luckylookout.com</a><br /><br />
- id: carlosfalchi
  alt: carlos falchi
  img: /images/portfolio/web/carlosfalchi.jpg
  thumbnail: /images/portfolio/web/carlosfalchi.png
  title: Development&nbsp;&nbsp;&#47;&#47;&nbsp;&nbsp;Carlos Falchi
  description: >
    <p>For this site I wrote XML builder files and integrated much of the flash into our rails framework. To a lesser extent I partially wired up the content management system in the back-end. All HTML and CSS and most Javascript was written by me. Collaborated with <a href="http://intersectnyc.com" target="_blank">Intersect NYC</a>.</p><a href="http://www.carlosfalchi.com/" target="_blank">http://www.carlosfalchi.com</a><br /><br />
- id: carlosfalchi_teaser
  alt: carlos falchteaser")
  img: /images/portfolio/web/carlosfalchi_teaser.jpg
  thumbnail: /images/portfolio/web/carlosfalchi_teaser.png
  title: Development&nbsp;&nbsp;&#47;&#47;&nbsp;&nbsp;Carlos Falchi Teaser
  description: >
    <p>Developed the frontend by writing HTML, CSS, and some very basic Ruby and JavaScript(JQuery) to produce web compliant Rails views in partnership with <a href="http://intersectnyc.com" target="_blank">Intersect NYC</a>.</p>
- id: coolercleanse
  alt: cooler cleanse
  img: /images/portfolio/web/coolercleanse.jpg
  thumbnail: /images/portfolio/web/coolercleanse.png
  title: Development&nbsp;&nbsp;&#47;&#47;&nbsp;&nbsp;Cooler Cleanse
  description: >
    <p>Partnered with <a href="http://intersectnyc.com" target="_blank">Intersect NYC </a> in developing the front end of this detox juice-centric e-commerce site. My role included writing the HTML, CSS, basic Ruby and some Javascript(JQuery) for the user interface.</p><a href="http://www.coolercleanse.com/" target="_blank">http://www.coolercleanse.com</a><br /><br />
- id: chilewich_wholesale
  alt: chilewicwholesale")
  img: /images/portfolio/web/chilewich_wholesale.jpg
  thumbnail: /images/portfolio/web/chilewich_wholesale.png
  title: Development&nbsp;&nbsp;&#47;&#47;&nbsp;&nbsp;Chilewich Wholesale
  description: >
    <p>Developed in partnership with <a href="http://intersectnyc.com" target="_blank">Intersect NYC</a>. This is a sub site for <a href="http://www.chilewich.com" target="_blank">www.chilewich.com</a> targeted at wholesale partners. My development work included writing HTML, CSS, basic Ruby and some Javascript for the user interface.</p><a href="http://www.chilewich.com/wholesale/" target="_blank">http://www.chilewich.com/wholesale</a>
- id: lucky_stylespotter
  alt: lucky style spotter
  img: /images/portfolio/web/lss.jpg
  thumbnail: /images/portfolio/web/lss.png
  title: Development&nbsp;&nbsp;&#47;&#47;&nbsp;&nbsp;Lucky Stylespotter
  description: >
    <p>Partnered with <a href="http://intersectnyc.com" target="_blank">Intersect NYC</a> in fully re-skinning the front end of this fashion setting user base driven site by writing HTML, CSS, basic Ruby and some Javascript for the user interface.</p><a href="http://stylespotter.luckymag.com/" target="_blank">http://stylespotter.luckymag.com</a>
- id: bond_and_bowery
  alt: bond and bowery
  img: /images/portfolio/web/bond_and_bowery.jpg
  thumbnail: /images/portfolio/web/bond_and_bowery.png
  title: Development&nbsp;&nbsp;&#47;&#47;&nbsp;&nbsp;Bond & Bowery
  description: >
    <p>Partnered with <a href="http://intersectnyc.com" target="_blank">Intersect NYC</a> to re-skin this vast site written almost entirely in PHP. I wrote new HTML, re-formatted existing HTML with CSS, wrote basic PHP, and Javascript for the entire user interface.</p><a href="http://www.bondandbowery.com/" target="_blank">http://www.bondandbowery.com</a><br /><br />
- id: chilewich
  alt: chilewich
  img: /images/portfolio/web/chilewich.jpg
  thumbnail: /images/portfolio/web/chilewich.png
  title: Development&nbsp;&nbsp;&#47;&#47;&nbsp;&nbsp;Chilewich
  description: >
    <p>Partnered with <a href="http://intersectnyc.com" target="_blank">Intersect NYC</a> to develop this striking and elegant e-commerce site, which emphasizes craftsmanship and well made designs with a focus on materials and textiles. I provided HTML, CSS, basic Ruby and some Javascript for the front end.</p><a href="http://www.chilewich.com/" target="_blank">http://www.chilewich.com</a>< br/><br />
- id: thornton
  alt: thornton tomasetti
  img: /images/portfolio/web/thornton.jpg
  thumbnail: /images/portfolio/web/thornton.png
  title: Development&nbsp;&nbsp;&#47;&#47;&nbsp;&nbsp;Thornton Tomasetti
  description: >
    <p>Partnered with <a href="http://intersectnyc.com" target="_blank">Intersect NYC</a> to develop the user interface for this site, which features a search engine for navigating through this structural engineering firm's portfolio. I provided HTML, CSS, basic Ruby and some Javascript for the front end.</p><a href="http://www.thorntontomasetti.com/" target="_blank">http://www.thorntontomasetti.com</a><br /><br />
- id: liz
  alt: liz
  img: /images/portfolio/web/liz.jpg
  thumbnail: /images/portfolio/web/liz.png
  title: Development&nbsp;&nbsp;&#47;&#47;&nbsp;&nbsp;Liz Claiborne
  description: >
    <p>Collaborated with <a href="http://intersectnyc.com" target="_blank">Intersect NYC</a> to develop the user interface to achieve the company's new vision and relaunching of the Liz brand. I provided HTML, CSS, and basic Ruby for the front end.
- id: citibabes
  alt: citibabesIntersect NYC</a>
  img: /images/portfolio/web/citibabes.jpg
  thumbnail: /images/portfolio/web/citibabes.png
  title: Development&nbsp;&nbsp;&#47;&#47;&nbsp;&nbsp;Citibabes
  description: >
    <p>This vibrant site is a one stop shop for city parents on the go. Partnered with <a href="http://intersectnyc.com" target="_blank">Intersect NYC</a> to develop the user interface by providing HTML, CSS, basic Ruby and some Javascript(JQuery) for the front end.</p><a href="http://www.citibabes.com/" target="_blank">http://www.citibabes.com</a><br /><br />
- id: mally_v1
  alt: mally beauty
  img: /images/portfolio/web/mally_v1.jpg
  thumbnail: /images/portfolio/web/mally_v1.png
  title: Development&nbsp;&nbsp;&#47;&#47;&nbsp;&nbsp;Mally Beauty
  description: >
    <p>This site focuses on it's community and sells an extensive line of beauty products. Partnered with <a href="http://intersectnyc.com" target="_blank">Intersect NYC</a>
- id: kates
  alt: kates paperie
  img: /images/portfolio/web/kates.jpg
  thumbnail: /images/portfolio/web/kates.png
  title: Development&nbsp;&nbsp;&#47;&#47;&nbsp;&nbsp;Kate's Paperie
  description: >
    <p>Partnered with <a href="http://intersectnyc.com" target="_blank">Intersect NYC</a> to develop the frontend by writing HTML, CSS, and some very basic Ruby to produce web compliant Rails views.</p><a href="http://www.katespaperie.com/" target="_blank">http://www.katespaperie.com</a><br /><br />
- id: kimara
  alt: kimara
  img: /images/portfolio/web/kimara.jpg
  thumbnail: /images/portfolio/web/kimara.png
  title: Development&nbsp;&nbsp;&#47;&#47;&nbsp;&nbsp;Kimara Ahnert
  description: >
    <p>Partnered with <a href="http://intersectnyc.com" target="_blank">Intersect NYC</a> to develop the frontend by writing HTML, CSS, and some very basic Ruby to produce web compliant Rails views for this high end beauty product e-commerce site.</p><a href="http://getmax.com/" target="_blank">http://getmax.com</a><br /><br />
- id: cinemax
  thumbnail: /images/portfolio/web/cinemax.png
  alt: cinemax
  img: /images/portfolio/web/cinemax.jpg
  title: Development&nbsp;&nbsp;&#47;&#47;&nbsp;&nbsp;Cinemax
  description: >
    <p>Collaborated with <a href="http://creativelabny.com/" target="_blank">CreativeLab</a>in re-skinning this site using XML, Flash, and HTML.</p><a href="http://getmax.com/" target="_blank">http://getmax.com</a><br /><br />