---
- id: bw1
  alt: black and white
  thumbnail: /images/portfolio/print/bw1.jpg
  img: /images/portfolio/print/bwcollage1.jpg
  title: Composing with random objects, part 1.1
  description: >
    <p>In a graduate school course called "Design Process; Visual Communication", we were given an assignment with the following parameters: we were to create three different compositions in black and white with objects randomly picked out from a bag. We were allowed to use a Xerox machine to create copies and we were allowed to alter the size of these objects. Each object was allowed to appear several times in the same composition. I picked a screw, an apple and a crayon tip. This is the first of three from the black and white series.</p>
- 
  - id: bw2
    alt: black and white
    thumbnail: /images/portfolio/print/bw2.jpg
    img: /images/portfolio/print/bwcollage2.jpg
    title: Composing with random objects, part 1.2
    description: >
      <p>This is the secod of three from the black and white series. This particular collage was received well and had the most positive critique, particularly due to the placing of the abstract crayon tip in the upper left. It is also my personal favorite from the series.</p>
  - id: bw3
    alt: black and white
    thumbnail: /images/portfolio/print/bw3.jpg
    img: /images/portfolio/print/bwcollage3.jpg
    title: Composing with random objects, part 1.3
    description: >
      <p>This is the third of three from the black and white series. I attempted to add additional contrast by applying image discontinuity, where an object is misaligned with itself.</p>
-
  - id: color1
    alt: color
    thumbnail: /images/portfolio/print/color1.jpg
    img: /images/portfolio/print/colorCollage1.jpg
    title: Composing with random objects, part 2.3
    description: >
      <p>Above is part 3 of the color collage series.</p>
  - id: color2
    alt: color
    thumbnail: /images/portfolio/print/color2.jpg
    img: /images/portfolio/print/colorCollage2.jpg
    title: Composing with random objects, part 2.1
    description: >
      <p>In the same graduate design course, we were given a similar assignment to the black and white collages, in which we were asked to create three surrealistic non-descriptive, non-narrative collages in color using at least 5 visual elements. This is a series of three stand alone pieces. Above is part one of the color collage series.</p>
- id: color3
  alt: color
  thumbnail: /images/portfolio/print/color3.jpg
  img: /images/portfolio/print/colorCollage3.jpg
  title: Composing with random objects, part 2.2
  description: >
    <p>Above is part two of the color collage series.</p>